// authentication related
export const GOOGLE_OAUTH2 = "GOOGLE_OAUTH2";
export const GOOGLE_CLIENT_LOADED = "GOOGLE_CLIENT_LOADED";

// statuses
export const STATUS_RESET = "STATUS_RESET";
export const STATUS_UPDATE_READY_TO_START = "STATUS_UPDATE_READY_TO_START";
export const STATUS_CHANNEL_LOADED = "STATUS_CHANNEL_LOADED";
export const STATUS_PLAYLIST_LOADED = "STATUS_PLAYLIST_LOADED";
export const STATUS_PLAYLIST_ITEMS_LOADED = "STATUS_PLAYLIST_ITEMS_LOADED";

// youtube related
export const YOUTUBE_RESET_DATA = "YOUTUBE_RESET_DATA";
export const YOUTUBE_ADD_CHANNELS = "YOUTUBE_ADD_CHANNELS";
export const YOUTUBE_ADD_PLAYLIST_IDS = "YOUTUBE_ADD_PLAYLIST_IDS";
export const YOUTUBE_ADD_PLAYLIST_ITEM_IDS = "YOUTUBE_ADD_PLAYLIST_ITEM_IDS";
export const YOUTUBE_ADD_VIDEOS = "YOUTUBE_ADD_VIDEOS";


// Progress bar
export const PROGRESS_RESET = "PROGRESS_RESET";
export const PROGRESS_CHANNELS_SET = "PROGRESS_CHANNELS_SET";
export const PROGRESS_CHANNELS_INCREMENT = "PROGRESS_CHANNELS_INCREMENT";
export const PROGRESS_VIDEOS_SET = "PROGRESS_VIDEOS_SET";
export const PROGRESS_VIDEO_INCREMENT = "PROGRESS_VIDEO_INCREMENT";


// Batch counter
export const BATCH_RESET_PLAYLIST_COUNT = "BATCH_RESET_PLAYLIST_COUNT";
export const BATCH_PLAYLIST_INCREMENT = "BATCH_PLAYLIST_INCREMENT";
export const BATCH_RESET_VIDEO_COUNT = "BATCH_RESET_VIDEO_COUNT";
export const BATCH_VIDEO_INCREMENT = "BATCH_VIDEO_INCREMENT";
