export const GOOGLE_OAUTH2 = "GOOGLE_OAUTH2";
export const GOOGLE_CLIENT_LOADED = "GOOGLE_CLIENT_LOADED";
export const YOUTUBE_RESET_DATA = "YOUTUBE_RESET_DATA";
export const YOUTUBE_GET_PLAYLISTS = "YOUTUBE_GET_PLAYLISTS";
export const YOUTUBE_GET_PLAYLIST_ITEMS = "YOUTUBE_GET_PLAYLIST_ITEMS";
export const YOUTUBE_GET_VIDEO_LIST = "YOUTUBE_GET_VIDEO_LIST";

// Progress counter
export const PROGRESS_PLAYLIST_RESET = "PROGRESS_PLAYLIST_RESET";
export const PROGRESS_PLAYLIST_INCREMENT = "PROGRESS_PLAYLIST_INCREMENT";
export const PROGRESS_PLAYLIST_ITEM_INCREMENT = "PROGRESS_PLAYLIST_ITEM_INCREMENT";
export const PROGRESS_VIDEO_INCREMENT = "PROGRESS_VIDEO_INCREMENT";