export const GOOGLE_OAUTH2 = "GOOGLE_OAUTH2";
export const GOOGLE_CLIENT_LOADED = "GOOGLE_CLIENT_LOADED";
export const YOUTUBE_GET_PLAYLISTS = "YOUTUBE_GET_PLAYLISTS";
export const YOUTUBE_GET_PLAYLIST_ITEMS = "YOUTUBE_GET_PLAYLIST_ITEMS";
export const YOUTUBE_GET_VIDEO_LIST = "YOUTUBE_GET_VIDEO_LIST";
// export const YOUTUBE_GET_VIDEO_LIST = "YOUTUBE_GET_VIDEO_LIST";